AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket with a semi-random name

Resources:
  BucketWithSemiRandomName:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
          - "alick-testbucket-${RandomGUID}"
          - RandomGUID:
              Fn::Select:
                - 0
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId

Outputs:
  S3Bucket:
    Description: "Bucket Created using this template."
    Value:
      Ref: BucketWithSemiRandomName
