AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket - Semi Random Name
    
Resources:
  BucketWithSemiRandomName:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName:
        !Sub
          - 'alick-testbucket-withsemirandomname-${RandomGUID}'
          - { RandomGUID: !Select [0, !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId ]]]] }
          
Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref BucketWithSemiRandomName
